### ISSUE TITLE
Crash after hitting an entity with a torch (incompatibility between soul fire'd & amendments)

### ISSUE THREAD

**Issue by Kloytz** [MehVahdJukaar/amendments#142]
[message.txt](https://github.com/user-attachments/files/17357565/message.txt)

**Comment by Kloytz** [comment]
![image](https://github.com/user-attachments/assets/486e26f6-0661-4441-84ac-d8eb57cba546)

**Comment by Crystal-Spider** [comment]
Hi! I'm Soul Fire'd dev, and I wanted to add something to this.

First, I'd like to link [the issue](https://github.com/Crystal-Nest/soul-fire-d/issues/59) opened on my repo just to keep things organized.  
Second, as I said in the screenshotted comment, the issue here is that you're compiling against the wrong version of Soul Fire'd, specifically 1.20.4-v4.0.1. This version is incompatible with 1.21.x. I will soon open a PR to fix this.

More details about the second point:

- Amendments declares Soul Fire'd optional dependency [here](https://github.com/MehVahdJukaar/amendments/blob/42bfa69be0de6d8a961e78ae2ca61bed6c40fa47/common/build.gradle#L28) and [here](https://github.com/MehVahdJukaar/amendments/blob/42bfa69be0de6d8a961e78ae2ca61bed6c40fa47/neoforge/build.gradle#L118), but in both places they use [this incompatible version](https://www.curseforge.com/minecraft/mc-mods/soul-fire-d/files/5448803).
- The fix I will apply in the PR is simply to follow the up-to-date guide on how to import Soul Fire'd, which you can find [here](https://github.com/Crystal-Nest/soul-fire-d/wiki/Getting-started#add-as-a-dependency).
- I will also remove Cobweb import from the Neoforge module as it should be useless when Soul Fire'd is imported as described above.

**Comment by Crystal-Spider** [comment]
Opened PR #143

**Comment by MehVahdJukaar** [comment]
should be fixed by that pr
