### ISSUE TITLE
[Suggestion]: Allow dripstone to fill cauldrons filled with modded fluids

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/amendments#153]
Amendment adds Acid Cauldrons and Purple Soda Cauldrons for Alex's Caves, which is awesome! However, they can't be filled with dripstone dripping their respective fluids like vanilla lava and water cauldrons can. It would be nice if we got compat for that as well

<img width="655" alt="Screenshot 2024-10-24 at 9 16 34 PM" src="https://github.com/user-attachments/assets/3731179f-74ad-40d3-8b1f-2871495a5c91">

(would be so cool fr)

**Comment by MehVahdJukaar** [comment]
I did think of that and in fact should already work. Does it not?

**Comment by thelegitdolt** [comment]
The dripstone wasn't making any particles so I thought it wasn't. Will test tomorrow

**Comment by thelegitdolt** [comment]
<img width="852" alt="Screenshot 2024-10-25 at 1 15 48 PM" src="https://github.com/user-attachments/assets/697d415c-c11e-4840-8435-ecf8ffe61cab">

tested on random tick speed 10000, doesn't seem to work

**Comment by MehVahdJukaar** [comment]
Do particles appear? What I meant to say before is that the ability to gather stuff from dristones is something to the discretion of the mod that adds fluids. They would have to add particles and such. Definitely not something amendments should do as many fluids should not be duplicate able with those

**Comment by MehVahdJukaar** [comment]
If they emit particles the cauldrons will accept them

**Comment by thelegitdolt** [comment]
But some mods don't even use cauldrons, it would be silly for them to add a particle system for dripstone, even if the liquid isn't too overpowered (like acid as shown). It would be cool to add it and allow players to blacklist/whitelist

**Comment by MehVahdJukaar** [comment]
Cauldrons implement the accept dripstone fluid method to convert that to cauldron fluid. That's all I need to do on my end. Adding particles for their fluids is vey much outside of the scope also because it would be adding s new mechanic to thsit said mod (the ability to have renewable/infinitr fluif of that type). Even if I were to dot hat how would I even find these mods to do this? It's not like I can do it for all fluids, it's obvious that some, or even all, should not be infinite. Adding dripstone stuff is something they definitely should be doing to march vanilla, heck I would even consider it a bug of them

**Comment by thelegitdolt** [comment]
OK i will go bug alex about it, if he doesn't want to  i can probably code something myself

**Comment by MehVahdJukaar** [comment]
A simple mixin in dripstone block will do. This is something a compat mod should handle so hand pick fluids that should do that
