### ISSUE TITLE
[1.20.1-CTD] SkullBlockMixin crash when exploring world.

### ISSUE THREAD

**Issue by Gbergz** [MehVahdJukaar/amendments#72]
Title ^

### Versions
MC: 1.20.1
Forge: 47.2.17
Amendments: 1.1.23
Supplementaries: 2.8.10

Crash Report: https://gist.githubusercontent.com/Gbergz/e85621c362819a94bcb6e2e231138e44/raw/074fd124e1e27ecd2e806ad780281d4a5e54404c/gistfile1.txt

**Comment by superdude808** [comment]
same error

**Comment by SirAdriel** [comment]
Having a similar issue but with Lecterns. "-1" error code. gave a crash log the first crash but stopped giving after the 2nd.

**Comment by EarthboundRune** [comment]
Still having this issue on the one that says fixed

**Comment by Veynam** [comment]
using the latest version of this mod at the time of writting, facing the same crash.

**Comment by TelepathicGrunt** [comment]
The crash is caused by this unsafe mixin attempting to make skull blocks waterloggable
https://github.com/MehVahdJukaar/amendments/blob/master/common/src/main/java/net/mehvahdjukaar/amendments/mixins/SkullBlockMixin.java

I recommend using this Statement library instead as it handles adding properties to vanilla blocks safely and properly. It's the only library/mod I really came across that did not blow up my mods and others with adding properties to vanilla blocks
https://www.curseforge.com/minecraft/mc-mods/statement
